// The song-independent half of a project export, embedded at build time:
// export_template_embedded.h, generated by tools/gen_template_embed.py from
// templates/manifest.txt by walking the #include graph.
#pragma once

#include <cstddef>
#include <string>
#include <vector>

// Bit flags: a template file carries the set of targets needing it. Keep in step
// with TARGETS in tools/gen_template_embed.py.
enum ExportTarget
{
  kExportTargetPebble  = 1,
  kExportTargetWin32   = 2,
  kExportTargetMicrow8 = 4,
  // Both WAV targets share one template set; they differ only in channel mode.
  kExportTargetWavStereo = 8,
  kExportTargetWavMono   = 16,
};

// The manifest's `wav` bit.
enum { kExportTemplateWav = kExportTargetWavStereo };

// TEXT: null-terminated `chunks`, split because MSVC caps a literal at 16380
// bytes. BINARY: `bytes`/`byteCount`, for data the text path would corrupt;
// never `subst`.
struct ExportTemplateFile
{
  const char*          path;      // destination, relative to the project root
  const char* const*   chunks;    // null-terminated; null for a binary file
  unsigned             targets;   // ExportTarget bit set
  bool                 subst;     // `{{NAME}}` placeholders, filled at write time
  const unsigned char* bytes;     // non-null for a binary file
  size_t               byteCount; // its length; no terminator to look for
};

// A `{{name}}` -> `value` replacement, only in files marked `subst`: `{{` is
// legal C, so a blanket pass would be unsafe.
struct ExportTemplateVar
{
  const char* name;   // without the braces: "SLUG", not "{{SLUG}}"
  std::string value;
};

enum ExportTemplateMode
{
  // A placeholder with no value is an error.
  kExportTemplateFill = 0,

  // Placeholders left as-is, for --dump-template's byte comparison with the repo.
  kExportTemplateRaw,
};

const ExportTemplateFile* ExportTemplateAll(size_t& count);

std::string ExportTemplateRead(const ExportTemplateFile& f);

// False with `err` on the first failure; files already written stay. `destDir`
// may or may not end in a separator.
bool ExportTemplateWrite(unsigned target, const std::string& destDir,
                         int& filesWritten, std::string& err,
                         const std::vector<ExportTemplateVar>& vars = {},
                         ExportTemplateMode mode = kExportTemplateFill);
