// Emits a standalone song.c rendering the recorded matrix: the compressed
// sequence and player (CompressSequence.cpp), one C function per sound used, and
// glue (constants, song_render_audio_batch()).
//
// The accumulator is fx16 (+-1.0 == +-65536). Fix bodies return fx16 directly;
// f64/f32 bodies convert via song_fx16_from_f64/_f32. PCM is fx16 * 32767 >> 16,
// clamped.
//
// An entry's two halves map independently, so every event is resolved twice,
// once per map, as live playback does. A visual case binds a sample only if its
// body calls smp(): song_voices[] is shared with the audio pass, and a stray bind
// would reseek its QOA stream mid-note.

#include "SongExport.h"

#include <cctype>
#include <cmath>
#include <cstdarg>
#include <cstdio>
#include <map>
#include <set>

#include "CompressSequence.h"
#include "Utf8File.h"

extern "C" {
#include "vm/vm_emit_c.h"
}

// song_dsp.h as a string, generated by CMake: export and playback share one source.
#include "song_dsp_embedded.h"

namespace {
// Sound name -> C identifier (leading digit -> '_', non-alnum -> '_'); "" -> "s".
std::string CIdent(const std::string& in) {
  std::string out;
  for (char c : in) {
    unsigned char u = (unsigned char)c;
    out += (isalnum(u) || c == '_') ? c : '_';
  }
  if (out.empty()) out = "s";
  if (isdigit((unsigned char)out[0])) out.insert(out.begin(), '_');
  return out;
}

long FxConst(double v, int fracBits) { return (long)std::llround(v * (double)(1LL << fracBits)); }

const char* CTypeName(CodeSynthType t) {
  switch (t) {
    case kCodeSynthFix: return "int";
    case kCodeSynthF32: return "float";
    case kCodeSynthF64: default: return "double";
  }
}

// Which of the 8 wrap args a body references; `pan` makes it stereo.
struct SoundArgUsage {
  bool used[kCodeSynthWrapParamCount] = {};
};

// Compiles `body` and appends its C function as `ident`, keeping only referenced
// params. Falls back to a silent stub with the error as a comment. `constPan`
// folds `pan` to 0.
void EmitSoundFunction(const std::string& ident, const std::string& body, CodeSynthType type,
                       const std::string& preludeBody, const cCodeSynthGlobals& globals,
                       RenderCtx* screen,
                       const char* globalsCPrefix, EmitCDedup& dedup,
                       std::string& out, SoundArgUsage& usage, VMType& retType,
                       bool constPan) {
  const char* cType = CTypeName(type);
  usage = SoundArgUsage{};

  auto emitStub = [&](const char* stage, const std::string& why) {
    out += "// '" + ident + "' failed to " + stage + " for export (" + why + "); emitting a silent stub.\n";
    out += std::string(cType) + " " + ident + "(void) { return 0; }\n\n";
    usage = SoundArgUsage{};
    // Already converted, so BuildFx16CallExpr adds nothing.
    retType = VMType{};
    retType.kind = (type == kCodeSynthFix) ? VMT_I32 : (type == kCodeSynthF32 ? VMT_F32 : VMT_F64);
    retType.len  = (type == kCodeSynthFix) ? 16 : 0;
  };

  VM* vm = nullptr;
  Parser* parser = nullptr;
  ParseResult* res = nullptr;
  std::string err;
  Func* fn = CodeSynthCompileForExport(body, CodeSynthExportWrapParamForType(type, constPan),
                                       preludeBody.c_str(), &globals, screen, &vm, &parser, &res, err,
                                       constPan);
  if (!fn) {
    emitStub("compile", err);
    return;
  }

  for (int i = 0; i < kCodeSynthWrapParamCount; i++) usage.used[i] = func_param_used(fn, i) != 0;
  retType = func_return_type(fn);

  // The only thing telling the two domains' instances apart in the emitted code.
  vm_set_globals_c_prefix(vm, globalsCPrefix);

  // Every body carries its own copy of the common helpers; content-hashed names
  // collapse them, so `dedup` must be shared by every call for one output.
  char* code = func_emit_c_named_dedup(fn, ident.c_str(), /*strip_unused=*/1, &dedup);
  if (code) { out += code; out += "\n"; vm->run.sys->free(code); }
  else      emitStub("emit C", vm_last_error(vm) ? vm_last_error(vm) : "out of memory");

  CodeSynthReleaseExport(vm, parser, res);
}

// `callExpr` as an fx16 sample. Fix lands by shift/cast; float results go
// through the song_fx16_from_* helpers.
std::string BuildFx16CallExpr(const std::string& callExpr, CodeSynthType type, VMType rt) {
  if (type == kCodeSynthFix) {
    if (rt.kind == VMT_I32) {
      int shift = rt.len;  // fixed-point shift, 0 if plain int
      if (shift == 16) return callExpr;
      if (shift < 16)  return "((int)(((long long)(" + callExpr + ")) << " + std::to_string(16 - shift) + "))";
      return "((int)(((long long)(" + callExpr + ")) >> " + std::to_string(shift - 16) + "))";
    }
    return (rt.kind == VMT_F32 ? "song_fx16_from_f32(" : "song_fx16_from_f64(") + callExpr + ")";
  }

  const char* cType = CTypeName(type);
  std::string asFloat;
  if (rt.kind == VMT_I32) {
    int shift = rt.len; // 0 == plain int
    asFloat = shift > 0
      ? "((" + std::string(cType) + ")(" + callExpr + ") / (" + cType + ")(1LL << " + std::to_string(shift) + "))"
      : "(" + std::string(cType) + ")(" + callExpr + ")";
  } else if ((type == kCodeSynthF32 && rt.kind == VMT_F32) || (type == kCodeSynthF64 && rt.kind == VMT_F64)) {
    asFloat = callExpr; // already the target representation
  } else {
    // An F64 body under f32, or vice versa.
    asFloat = "(" + std::string(cType) + ")(" + callExpr + ")";
  }
  return (type == kCodeSynthF32 ? "song_fx16_from_f32(" : "song_fx16_from_f64(") + asFloat + ")";
}

// %g prints whole numbers bare, and "1f" is not a C token: add ".0".
std::string FmtG(double v, int prec) {
  char buf[64];
  snprintf(buf, sizeof(buf), "%.*g", prec, v);
  std::string s = buf;
  if (s.find_first_not_of("+-0123456789") == std::string::npos) s += ".0";
  return s;
}

std::string FmtConst(double v, CodeSynthType type) {
  char buf[64];
  switch (type) {
    case kCodeSynthFix: snprintf(buf, sizeof(buf), "%ldL", FxConst(v, kCodeSynthFxShift)); break;
    case kCodeSynthF32: return FmtG(v, 9) + "f";
    case kCodeSynthF64: default: return FmtG(v, 17);
  }
  return buf;
}

// synthIdx < 0: this map has nothing for the note.
struct ResolvedVoice {
  int           synthIdx = -1;
  std::string   ident;                  // C identifier base for the sound's name
  CodeSynthType type = kCodeSynthF64;
  double        freqMul = 1.0;          // 2^((note+transpose-69)/12), relative to A4
  int           rootNote = 0;           // the sound's own defining note (for RATE)
};

const CodeSynthEntry* FindEntry(const std::vector<CodeSynthEntry>& entries, const std::string& name) {
  for (const CodeSynthEntry& e : entries)
    if (e.name == name) return &e;
  return nullptr;
}

ResolvedVoice ResolveVoice(const cCodeSynthReadonly& ro, const std::vector<CodeSynthEntry>& entries,
                           int channel, int note) {
  ResolvedVoice v;
  int ch0 = channel & 0x0f;
  int idx1 = (note >= 0 && note < 128) ? ro.map[ch0 * 128 + note] : 0;
  v.synthIdx = idx1 - 1;
  if (v.synthIdx < 0) return v;

  const std::string& name = ro.synthName[v.synthIdx];
  // Pitched against A4, not the root note, as handleMidi does.
  v.freqMul  = CodeSynthSemitoneRatio(note + ro.synthTranspose[v.synthIdx] - 69);
  v.rootNote = ro.synthRootNote[v.synthIdx];
  v.ident    = CIdent(name);
  if (const CodeSynthEntry* e = FindEntry(entries, name)) v.type = e->type;
  return v;
}

// event id == row + kEventIdBase
struct EventInfo {
  int  eventId;
  int  note;             // row's MIDI note (names the HZ/XRATE/NN/RATE constants)
  bool hasVel;           // velocity < full -> apply VELMUL
  long velFx;            // fx16 of velocity / 127 (velocity mixing is always fx16)
  ResolvedVoice audio;   // through the sound map
  ResolvedVoice visual;  // through the visual map (may be a DIFFERENT entry)
};

// A rate-dependent constant over SONG_SAMPLE_RATE, so re-#defining the rate
// retimes and repitches. Fix goes via the 64-bit SONG_FX22_PER_SAMPLE.
std::string PerSampleExpr(double perSecond, CodeSynthType type) {
  char b[96];
  switch (type) {
    case kCodeSynthFix: {
      long long num_fx22 = (long long)std::llround(perSecond * (double)(1LL << kCodeSynthFxShift));
      snprintf(b, sizeof(b), "SONG_FX22_PER_SAMPLE(%lldLL)", num_fx22);
      break;
    }
    case kCodeSynthF32:
      return "(" + FmtG(perSecond, 9) + "f / (float)SONG_SAMPLE_RATE)";
    case kCodeSynthF64: default:
      return "(" + FmtG(perSecond, 17) + " / (double)SONG_SAMPLE_RATE)";
  }
  return b;
}

std::string ConstName(const std::string& ident, int note, const char* suffix) {
  return ident + "_" + std::to_string(note) + "_" + suffix;
}

// t/phase/beat arguments. Fix multiplies in 64 bits, since beat counts the whole song.
std::string ScaledExpr(const std::string& countExpr, const std::string& perSample, CodeSynthType type) {
  switch (type) {
    case kCodeSynthFix: return "((int)((long long)" + countExpr + " * (long long)" + perSample + "))";
    case kCodeSynthF32:  return "((float)" + countExpr + " * " + perSample + ")";
    case kCodeSynthF64: default: return "((double)" + countExpr + " * " + perSample + ")";
  }
}

// Steps off SONG_SAMPLES_PER_SONGTICK so beat can't disagree with the grid. Fix
// keeps 20 extra fractional bits, or rounding would drift audibly over a song.
std::string BeatScaledExpr(const std::string& countExpr, CodeSynthType type) {
  switch (type) {
    case kCodeSynthFix:
      return "((int)(((long long)" + countExpr + " * SONG_BEAT_FX42_PER_SAMPLE) >> 20))";
    case kCodeSynthF32:
      return "((float)" + countExpr + " / (4.0f * (float)SONG_SAMPLES_PER_SONGTICK))";
    case kCodeSynthF64: default:
      return "((double)" + countExpr + " / (4.0 * (double)SONG_SAMPLES_PER_SONGTICK))";
  }
}

// Per-row process order for CompressEventMatrix, resolved through the audio map
// (which claims every entry). Must be computed identically for song.c and
// song.h, or their channel counts differ.
std::vector<int> BuildRowOrders(const SongExportInput& in) {
  const int numRows = (int)in.seq.rows.size();
  std::vector<int> orders(numRows, 0);
  if (numRows == 0 || in.entries.empty()) return orders;

  // No orders: the unconstrained path is identical.
  bool any = false;
  for (const CodeSynthEntry& e : in.entries) if (e.order != 0) { any = true; break; }
  if (!any) return orders;

  std::string spec = CodeSynthSerializeEntries(in.entries);
  cCodeSynthReadonly ro;
  char dbg[256] = {0};
  CodeSynthParse(spec.c_str(), in.workingDir.c_str(), &ro,
                 (int)sizeof(dbg), dbg, in.screen, /*forVisual=*/false);

  for (int r = 0; r < numRows; r++) {
    const SongEventRow& row = in.seq.rows[r];
    const int ch0  = row.channel & 0x0f;
    const int idx1 = (row.note >= 0 && row.note < 128) ? ro.map[ch0 * 128 + row.note] : 0;
    if (idx1 > 0) orders[r] = ro.synthOrder[idx1 - 1];
  }
  return orders;
}
} // namespace

bool SongExportGenerateC(const SongExportInput& in, std::string& out, std::string& err,
                         int* outChannels)
{
  out.clear();
  err.clear();
  // Set before any early return: callers forward it to SongExportGenerateH.
  if (outChannels) *outChannels = 1;

  if (in.seq.empty()) { err = "no recorded sequence"; return false; }
  if (in.entries.empty()) { err = "no sound entries"; return false; }

  const std::vector<SongEventRow>& rows = in.seq.rows;
  const int numRows = (int)rows.size();

  // 1. Compress; must match SongExportGenerateH's call.
  CompressedSequence cs = CompressEventMatrix(in.seq.matrix, numRows, in.seq.cols, BuildRowOrders(in));
  if (cs.numRows == 0) { err = "event matrix failed to compress"; return false; }

  // 2. Compile the sounds offline, both halves.
  std::string spec = CodeSynthSerializeEntries(in.entries);
  cCodeSynthReadonly roAudio, roVisual;
  char dbgAudio[1024] = {0}, dbgVisual[1024] = {0};
  bool haveAudio  = CodeSynthParse(spec.c_str(), in.workingDir.c_str(), &roAudio,
                                   (int)sizeof(dbgAudio), dbgAudio, in.screen, /*forVisual=*/false);
  bool haveVisual = CodeSynthParse(spec.c_str(), in.workingDir.c_str(), &roVisual,
                                   (int)sizeof(dbgVisual), dbgVisual, in.screen, /*forVisual=*/true);
  if (!haveAudio && !haveVisual) {
    err = std::string("code compiled nothing: ") + dbgAudio;
    return false;
  }

  const double sr = in.sampleRate > 0.0 ? in.sampleRate : 44100.0;
  const double bpm = in.bpm > 0.0 ? in.bpm : 120.0;
  const int batchSize = in.batchSize > 0 ? in.batchSize : 32;

  int samplesPerSongTick = (int)(in.seq.samplesPerStep > 0.0
                                   ? in.seq.samplesPerStep
                                   : sr * 60.0 / bpm / 4.0 + 0.5);
  if (samplesPerSongTick < 1) samplesPerSongTick = 1;

  // `beat` steps off SONG_SAMPLES_PER_SONGTICK; `bpm` only fills the grid when the
  // sequence has no step length.

  std::vector<EventInfo> events;
  events.reserve(numRows);
  std::set<int> usedSynths;       // into roAudio.synth[]
  std::set<int> usedVisualSynths; // into roVisual.synth[]

  for (int r = 0; r < numRows; r++) {
    const SongEventRow& row = rows[r];

    EventInfo e;
    e.eventId = r + kEventIdBase;
    e.note    = row.note;
    e.audio   = ResolveVoice(roAudio,  in.entries, row.channel, row.note);
    e.visual  = ResolveVoice(roVisual, in.entries, row.channel, row.note);

    // Placeholder slots for a missing half: emit nothing.
    if (e.audio.synthIdx >= 0) {
      const CodeSynthEntry* ae = FindEntry(in.entries, roAudio.synthName[e.audio.synthIdx]);
      if (ae && !ae->body.empty()) usedSynths.insert(e.audio.synthIdx);
      else e.audio.synthIdx = -1;
    }
    if (e.visual.synthIdx >= 0) {
      const CodeSynthEntry* ve = FindEntry(in.entries, roVisual.synthName[e.visual.synthIdx]);
      if (ve && !ve->visualBody.empty()) usedVisualSynths.insert(e.visual.synthIdx);
      else e.visual.synthIdx = -1;
    }

    // Velocity scaling is always fx16.
    e.hasVel = (row.velocity < 127);
    e.velFx  = FxConst(row.velocity / 127.0, 16);
    events.push_back(e);
  }

  // 3. Assemble the file. `buf` fits the longest line the switches produce.
  char buf[4096];
  auto linef = [&](const char* fmt, ...) {
    va_list ap; va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    out += buf; out += "\n";
  };

  const int srInt = (int)(sr + 0.5);

  linef("// Auto-generated by \"Save C Song\". Standalone renderer for the recorded");
  linef("// step sequence. Export sample rate %d Hz, song tick %d samples (1/16 note)",
        srInt, samplesPerSongTick);
  linef("// -- but all rate-dependent constants below are expressed over the");
  linef("// SONG_SAMPLE_RATE macro, so #defining it to another rate (e.g. a 16 kHz");
  linef("// Pebble build) before #including this file repitches AND retimes the song.");
  linef("// Link with common/math_pure.c, common/math_fixedp.c, and vscreen.c (visual");
  linef("// functions -- see song_visual_render below -- call vscreen_putpixel_*).");
  linef("");
  linef("#include \"common/math_pure.h\"");
  linef("#include \"common/math_fixedp.h\"");
  linef("#include \"%s\"", in.vscreenInclude.empty()
                             ? "apps/madteasynth/vscreen.h"
                             : in.vscreenInclude.c_str());
  linef("");
  linef("// Generated alongside this file (see SongExport.h). Defines");
  linef("// SONG_CHANNEL_COUNT and song_SongState -- the layout this file's player");
  linef("// is written against, and the one any caller allocating a state must use.");
  linef("#include \"song.h\"");
  linef("");
  // Every rate-dependent constant derives from this, so one #define resamples the
  // whole song.
  linef("#ifndef SONG_SAMPLE_RATE");
  linef("#define SONG_SAMPLE_RATE %d", srInt);
  linef("#endif");
  linef("");
  // round(num_fx22 / SONG_SAMPLE_RATE), with num_fx22 64-bit.
  linef("#define SONG_FX22_PER_SAMPLE(num_fx22) ((int)(((num_fx22) + SONG_SAMPLE_RATE / 2) / SONG_SAMPLE_RATE))");
  linef("");
  // Sample-rate correction lives in song_smp_stream's sr_ratio, so rate_scale_fx is raw.
  linef("");
  // Guarded so an embedder can pin it.
  linef("#ifndef SONG_SAMPLES_PER_SONGTICK");
  linef("#define SONG_SAMPLES_PER_SONGTICK ((int)(((long long)%d * SONG_SAMPLE_RATE + %d / 2) / %d))",
        samplesPerSongTick, srInt, srInt);
  linef("#endif");
  linef("");
  // `beat` step: one beat per four song ticks, so it is locked to the grid. 20
  // fractional bits beyond fx22, shifted off after the 64-bit multiply.
  linef("#define SONG_BEAT_FX42_PER_SAMPLE (((1LL << 42) + 2LL * SONG_SAMPLES_PER_SONGTICK) / (4LL * SONG_SAMPLES_PER_SONGTICK))");
  linef("");

  // (1) sequence tables + song_sequence_tick()
  out += "// ===== sequence data + player =====\n";
  out += ExportToCSource(cs, "song");
  out += "\n";

  auto hasSample = [&](int synthIdx) {
    return synthIdx >= 0 && roAudio.synth[synthIdx].sample
        && roAudio.synth[synthIdx].sample->qoa_data && roAudio.synth[synthIdx].sample->qoa_len > 0;
  };
  auto synthType = [&](int synthIdx) {
    const CodeSynthEntry* e = FindEntry(in.entries, roAudio.synthName[synthIdx]);
    return e ? e->type : kCodeSynthF64;
  };

  // Only the smp_* wrappers actually called, to keep -Wunused-function quiet.
  bool needSmpF32 = false, needSmpF64 = false, needSmpFx22 = false;
  for (int synthIdx : usedSynths) {
    if (!hasSample(synthIdx)) continue;
    CodeSynthType st = synthType(synthIdx);
    if (st == kCodeSynthF32)      needSmpF32  = true;
    else if (st == kCodeSynthFix) needSmpFx22 = true;
    else                          needSmpF64  = true;
  }
  if (needSmpF32 || needSmpF64 || needSmpFx22) {
    if (needSmpF32)  out += "static float  smp_f32(float rate, float filter);\n";
    if (needSmpF64)  out += "static double smp_f64(double rate, double filter);\n";
    if (needSmpFx22) out += "static int    smp_fx22(int rate, int filter);\n";
    out += "\n";
  }

  // (2) One C function per sound used. `dedup` keeps shared helpers to one definition.
  const std::string soundPrelude  = CodeSynthPreludeFor(in.entries, /*forVisual=*/false);
  const std::string visualPrelude = CodeSynthPreludeFor(in.entries, /*forVisual=*/true);

  // Each domain's layout, fixed before any body compiles.
  cCodeSynthGlobals soundGlobals, visualGlobals;
  const std::string commonBody = CodeSynthCommonBody(in.entries);
  soundGlobals.Build(commonBody, CodeSynthGlobalsBody(in.entries, /*forVisual=*/false), in.screen);
  visualGlobals.Build(commonBody, CodeSynthGlobalsBody(in.entries, /*forVisual=*/true), in.screen);

  const char* kSoundGlobalsPrefix  = "song_ga.";
  const char* kVisualGlobalsPrefix = "song_gv.";

  EmitCDedup dedup = {};

  // Storage for both domains, from the declaration-pass VMs, which alone hold
  // complete tables.
  if (!soundGlobals.Empty() || !visualGlobals.Empty()) {
    out += "// ===== shared variables =====\n";
    out += soundGlobals.EmitC("song_globals_audio_t", "song_ga");
    out += visualGlobals.EmitC("song_globals_visual_t", "song_gv");
    out += "\n";
  }

  // Forced mono folds `pan` to 0 instead of passing it to every call.
  const bool constPanAudio = (in.channelMode == kSongChannelsMono);

  out += "// ===== sound functions =====\n";
  std::map<int, SoundArgUsage> synthUsage;  // synthIdx -> referenced wrap args
  std::map<int, VMType>        synthRetType;  // synthIdx -> inferred return type
  std::map<int, std::string>   synthIdent;   // synthIdx -> emitted C function name
  for (int synthIdx : usedSynths) {
    const std::string& name = roAudio.synthName[synthIdx];
    const CodeSynthEntry* entry = FindEntry(in.entries, name);
    std::string ident = CIdent(name);
    synthIdent[synthIdx] = ident;
    EmitSoundFunction(ident, entry ? entry->body : std::string(),
                      entry ? entry->type : kCodeSynthF64, soundPrelude, soundGlobals,
                      in.screen, kSoundGlobalsPrefix, dedup,
                      out, synthUsage[synthIdx], synthRetType[synthIdx], constPanAudio);
  }
  out += "\n";

  // Output channels, knowable only now: Auto asks whether any body reads `pan`.
  bool anyPanned = false;
  for (const auto& kv : synthUsage)
    if (kv.second.used[kCodeSynthPanParamIndex]) { anyPanned = true; break; }

  const int outputChannels =
      (in.channelMode == kSongChannelsStereo) ? 2 :
      (in.channelMode == kSongChannelsAuto && anyPanned) ? 2 : 1;
  const bool stereoOut = (outputChannels == 2);
  if (outChannels) *outChannels = outputChannels;

  // Mono output: one accumulator, panned sounds render once at pan = 0. Stereo:
  // panned sounds render per channel, unpanned ones once into both.
  auto isStereoSound = [&](int synthIdx) {
    std::map<int, SoundArgUsage>::const_iterator it = synthUsage.find(synthIdx);
    return it != synthUsage.end() && it->second.used[kCodeSynthPanParamIndex];
  };

  // (2b) Visual functions, as "<ident>_visual", indexed by roVisual's own slots.
  out += "// ===== visual functions =====\n";
  std::map<int, SoundArgUsage> visualUsage;
  std::map<int, VMType>        visualRetType;
  std::map<int, std::string>   visualIdent;
  std::map<int, std::string>   visualBase;  // synthIdx -> ident WITHOUT the _visual suffix
  std::map<int, bool>          visualSmp;   // synthIdx -> body actually calls smp()
  for (int synthIdx : usedVisualSynths) {
    const std::string& name = roVisual.synthName[synthIdx];
    const CodeSynthEntry* entry = FindEntry(in.entries, name);
    if (!entry || entry->visualBody.empty()) continue;

    std::string base   = CIdent(name);
    std::string vIdent = base + "_visual";
    const size_t bodyStart = out.size();
    EmitSoundFunction(vIdent, entry->visualBody, entry->type, visualPrelude, visualGlobals,
                      in.screen, kVisualGlobalsPrefix, dedup,
                      out, visualUsage[synthIdx], visualRetType[synthIdx], /*constPan=*/true);
    visualIdent[synthIdx] = vIdent;
    visualBase[synthIdx]  = base;
    // Whether this visual body calls smp(): only those get a bind, since a bind from
    // the visual pass can reseek the audio pass's decoder.
    {
      const std::string body = out.substr(bodyStart);
      // Whole-identifier match.
      auto callsFn = [&](const char* fn) {
        for (size_t p = body.find(fn); p != std::string::npos; p = body.find(fn, p + 1)) {
          if (p == 0) return true;
          unsigned char prev = (unsigned char)body[p - 1];
          if (!isalnum(prev) && prev != '_') return true;
        }
        return false;
      };
      visualSmp[synthIdx] = callsFn("smp_fx22(") || callsFn("smp_f64(") || callsFn("smp_f32(");
    }
  }
  out += "\n";

  // (2c) sample data and smp helpers
  out += "// ===== sample data + smp helpers =====\n";
  std::vector<int> sampleSynths;
  for (int synthIdx : usedSynths)
    if (hasSample(synthIdx)) sampleSynths.push_back(synthIdx);

  if (!sampleSynths.empty()) {
    // The same DSP as live playback.
    out += "// ---- shared sample DSP (inlined from codesynth/song_dsp.h) ----\n";
    out += "#define NEED_SMP\n";
    out += kSongDspSource;
    out += "\n\n";

    // One streaming voice per song channel.
    out += "static song_smp_voice_t song_voices[SONG_CHANNEL_COUNT];\n";
    out += "static song_smp_voice_t *song_current_voice;\n";
    if (needSmpF32)  out += "static float  smp_f32(float rate, float filter)   { return song_smp_stream(song_current_voice, rate, filter); }\n";
    if (needSmpF64)  out += "static double smp_f64(double rate, double filter) { return (double)song_smp_stream(song_current_voice, (float)rate, (float)filter); }\n";
    if (needSmpFx22) out += "static int    smp_fx22(int rate, int filter)      { return song_smp_stream_fx(song_current_voice, rate, filter); }\n";
    out += "\n";

    for (int synthIdx : sampleSynths) {
      const cSampleData* s = roAudio.synth[synthIdx].sample;
      const std::string& ident = synthIdent[synthIdx];
      snprintf(buf, sizeof(buf), "static const unsigned char smp_%s_qoa[%d] = {", ident.c_str(), s->qoa_len);
      out += buf;
      for (int i = 0; i < s->qoa_len; i++) {
        if (i % 20 == 0) out += "\n    ";
        char hex[8];
        snprintf(hex, sizeof(hex), "0x%02x,", s->qoa_data[i]);
        out += hex;
      }
      out += "\n};\n\n";

      // Raw degrade compensation; output-rate tracking is sr_ratio's job.
      snprintf(buf, sizeof(buf), "static const song_sample_t smp_%s = {smp_%s_qoa, %d, %d, %dLL, %d};\n\n",
               ident.c_str(), ident.c_str(), s->qoa_len, s->num_samples, s->rate_scale_fx, s->sample_rate);
      out += buf;
    }
  }
  out += "\n";

  // (3) constants + song_render_audio_batch()
  out += "// ===== render glue =====\n";
  linef("#define BATCHSIZE %d", batchSize);
  linef("// fx16 * fx16 -> fx16 (e.g. a velocity multiplier on a sound's fx16 return).");
  linef("#define mul16(a, b) ((int)(((long long)(a) * (long long)(b)) >> 16))");
  linef("");
  linef("// fx16 sample (+-1.0 == +-65536) -> clamped 16-bit PCM (+-32767).");
  linef("static short int song_fx16_to_pcm16(int v) {");
  linef("    long long p = ((long long)v * 32767) >> 16;");
  linef("    if (p > 32767) p = 32767;");
  linef("    if (p < -32768) p = -32768;");
  linef("    return (short int)p;");
  linef("}");
  linef("");

  // Only the float->fx16 helpers the code calls.
  {
    bool needF64 = false, needF32 = false;
    for (int synthIdx : usedSynths) {
      CodeSynthType st = synthType(synthIdx);
      VMType rt = synthRetType[synthIdx];
      if (st == kCodeSynthF64) {
        needF64 = true;
      } else if (st == kCodeSynthF32) {
        needF32 = true;
      } else if (st == kCodeSynthFix) {
        if (rt.kind == VMT_F64) needF64 = true;
        if (rt.kind == VMT_F32) needF32 = true;
      }
    }
    if (needF32) needF64 = true; // song_fx16_from_f32 forwards to the f64 helper
    if (needF64 || needF32) {
      linef("// Sound double/float return value -> fx16, round-to-nearest, NaN/overflow-safe.");
      linef("static int song_fx16_from_f64(double r) {");
      linef("    if (r != r) r = 0.0;");
      linef("    double scaled = r * 65536.0;");
      linef("    if (scaled > 2147483520.0) scaled = 2147483520.0;");
      linef("    if (scaled < -2147483520.0) scaled = -2147483520.0;");
      linef("    return (int)(scaled + (scaled >= 0.0 ? 0.5 : -0.5));");
      linef("}");
      if (needF32) {
        linef("static int song_fx16_from_f32(float r) {");
        linef("    return song_fx16_from_f64((double)r);");
        linef("}");
      }
      linef("");
    }
  }

  // Per-(sound, note) constants, deduplicated by name, only for args a body reads.
  // `t` and `beat` need none.
  std::set<std::string> emittedDefs;
  auto emitVoiceConsts = [&](const ResolvedVoice& v, const SoundArgUsage& u, int note) {
    if (v.synthIdx < 0) return;
    double hz = 440.0 * v.freqMul;
    if (u.used[1]) { // hz: the note's absolute frequency, as a plain constant
      std::string name = ConstName(v.ident, note, "HZ");
      if (emittedDefs.insert(name).second)
        linef("#define %-24s %s", name.c_str(), FmtConst(hz, v.type).c_str());
    }
    if (u.used[2]) { // phase = t*hz -> per-sample scale factor hz/sr (over SONG_SAMPLE_RATE)
      std::string name = ConstName(v.ident, note, "XRATE");
      if (emittedDefs.insert(name).second)
        linef("#define %-24s %s", name.c_str(), PerSampleExpr(hz, v.type).c_str());
    }
    if (u.used[3]) { // note: the played MIDI note number, as a plain constant
      std::string name = ConstName(v.ident, note, "NN");
      if (emittedDefs.insert(name).second)
        linef("#define %-24s %s", name.c_str(), FmtConst((double)note, v.type).c_str());
    }
    if (u.used[5]) { // rate: pitch ratio of played note to the sound's root note
      // (1.0 at root); output-rate compensation lives in rate_scale_fx.
      std::string name = ConstName(v.ident, note, "RATE");
      if (emittedDefs.insert(name).second)
        linef("#define %-24s %s", name.c_str(),
              FmtConst(CodeSynthSemitoneRatio(note - v.rootNote), v.type).c_str());
    }
  };
  // vel: the raw velocity in the body's domain, separate from the fx16 VELMUL
  // multiplier. Keyed by (ident, note, velocity).
  auto emitVelConst = [&](const ResolvedVoice& v, const SoundArgUsage& u, int note, int velocity) {
    if (v.synthIdx < 0 || !u.used[6]) return;
    std::string name = v.ident + "_" + std::to_string(note) + "_v"
                      + std::to_string(velocity) + "_VEL";
    if (emittedDefs.insert(name).second)
      linef("#define %-24s %s", name.c_str(), FmtConst((double)velocity, v.type).c_str());
  };
  for (const EventInfo& e : events) {
    emitVoiceConsts(e.audio,  synthUsage[e.audio.synthIdx],   e.note);
    emitVoiceConsts(e.visual, visualUsage[e.visual.synthIdx], e.note);
    int velocity = rows[e.eventId - kEventIdBase].velocity;
    emitVelConst(e.audio,  synthUsage[e.audio.synthIdx],   e.note, velocity);
    emitVelConst(e.visual, visualUsage[e.visual.synthIdx], e.note, velocity);
    if (e.hasVel && e.audio.synthIdx >= 0) {
      std::string velName = e.audio.ident + "_" + std::to_string(e.note) + "_v"
                          + std::to_string(velocity) + "_VELMUL";
      if (emittedDefs.insert(velName).second)
        linef("#define %-24s %ld", velName.c_str(), e.velFx);
    }
  }
  linef("");

  // The argument list for one call site. `byRef` (grouped) reads the per-note
  // values off the table row `p`. `pan` is a per-call literal in the body's domain.
  auto buildCallArgs = [&](const ResolvedVoice& v, const SoundArgUsage& u, int note,
                           const char* sampExpr, const std::string& absExpr, int velocity,
                           bool byRef, double pan) {
    std::string exprs[kCodeSynthWrapParamCount];
    exprs[0] = ScaledExpr(sampExpr, PerSampleExpr(1.0, v.type), v.type);
    exprs[1] = byRef ? "p.hz" : ConstName(v.ident, note, "HZ");
    if (u.used[2]) exprs[2] = ScaledExpr(sampExpr,
                                         byRef ? "p.xrate" : ConstName(v.ident, note, "XRATE"),
                                         v.type);
    exprs[3] = byRef ? "p.nn" : ConstName(v.ident, note, "NN");
    if (u.used[4]) exprs[4] = BeatScaledExpr(absExpr, v.type);
    exprs[5] = byRef ? "p.rate" : ConstName(v.ident, note, "RATE");
    if (u.used[6]) exprs[6] = byRef ? "p.vel"
                                    : v.ident + "_" + std::to_string(note) + "_v"
                                      + std::to_string(velocity) + "_VEL";
    if (u.used[kCodeSynthPanParamIndex])
      exprs[kCodeSynthPanParamIndex] = FmtConst(pan, v.type);

    std::string args;
    for (int a = 0; a < kCodeSynthWrapParamCount; a++) {
      if (!u.used[a]) continue;
      if (!args.empty()) args += ", ";
      args += exprs[a];
    }
    return args;
  };

  // The bind is loop-invariant and the note_sample stamp is not, so the inlined
  // shape hoists the bind.
  auto sampleBind = [&](const ResolvedVoice& v) {
    if (!hasSample(v.synthIdx)) return std::string();
    return "song_smp_bind(&song_voices[channel_id], &smp_" + v.ident
         + ", SONG_SAMPLE_RATE); song_current_voice = &song_voices[channel_id]; ";
  };
  auto sampleStamp = [&](const ResolvedVoice& v) {
    if (!hasSample(v.synthIdx)) return std::string();
    return std::string("song_voices[channel_id].note_sample = samp; ");
  };
  auto samplePreamble = [&](const ResolvedVoice& v) { return sampleBind(v) + sampleStamp(v); };

  // Duplicate rows (re-triggers) render identically: one body behind fall-through labels.
  auto sameIdentity = [&](const EventInfo& a, const EventInfo& b) {
    const SongEventRow& ra = rows[a.eventId - kEventIdBase];
    const SongEventRow& rb = rows[b.eventId - kEventIdBase];
    return ra.channel == rb.channel && ra.note == rb.note && ra.velocity == rb.velocity;
  };

  auto emitFallThroughLabels = [&](size_t first, size_t last, const char* indent) {
    for (size_t ek = first; ek + 1 < last; ek++)
      linef("%scase %d:", indent, events[ek].eventId);
  };

  // Only t, phase and a sample stamp read `samp`.
  auto caseUsesSamp = [&](const EventInfo& e) {
    if (e.audio.synthIdx < 0) return false;
    const SoundArgUsage& u = synthUsage[e.audio.synthIdx];
    return u.used[0] || u.used[2] || hasSample(e.audio.synthIdx);
  };

  // One event's fx16 contribution per sample, identical in every loop shape.
  // Returned by value: linef() would alias `buf`.
  auto buildMixExpr = [&](const EventInfo& e, double pan) {
    const SoundArgUsage& u = synthUsage[e.audio.synthIdx];
    int velocity = rows[e.eventId - kEventIdBase].velocity;
    std::string callExpr = e.audio.ident + "("
                         + buildCallArgs(e.audio, u, e.note, "samp", "(sample_id + i)", velocity,
                                         /*byRef=*/false, pan) + ")";
    std::string expr = BuildFx16CallExpr(callExpr, e.audio.type, synthRetType[e.audio.synthIdx]);
    if (e.hasVel)
      expr = "mul16(" + expr + ", " + e.audio.ident + "_" + std::to_string(e.note)
           + "_v" + std::to_string(velocity) + "_VELMUL)";
    return expr;
  };

  // Accumulate statements, shared by the inlined and grouped layouts:
  //   mono out              acc[i] += <mix pan=0>;
  //   stereo out, mono snd  s = <mix pan=0>; accL[i] += s; accR[i] += s;
  //   stereo out, panned    accL[i] += <mix pan=-1>; accR[i] += <mix pan=+1>;
  // `s` avoids rendering an unpanned sound twice; it is declared outside the switch.
  auto buildAccum = [&](int synthIdx, auto&& mix) -> std::string {
    if (!stereoOut) return "acc[i] += " + mix(0.0) + ";";
    if (isStereoSound(synthIdx))
      return "accL[i] += " + mix(-1.0) + "; accR[i] += " + mix(1.0) + ";";
    return "s = " + mix(0.0) + "; accL[i] += s; accR[i] += s;";
  };

  SongSndLoopShape sndLoopShape = in.sndLoopShape;
  if (sndLoopShape == kSongSndLoopAuto) {
    int soundCases = 0;
    for (size_t ei = 0; ei < events.size(); ) {
      size_t ej = ei + 1;
      while (ej < events.size() && sameIdentity(events[ei], events[ej])) ej++;
      if (events[ej - 1].audio.synthIdx >= 0) soundCases++;
      ei = ej;
    }
    sndLoopShape = (soundCases < kSongSndLoopAutoSharedBelow) ? kSongSndLoopShared : kSongSndLoopGrouped;
    linef("// sound loop shape: auto -> %s (%d sounding events)",
          sndLoopShape == kSongSndLoopShared ? "combined" : "per instrument", soundCases);
    linef("");
  }
  const bool inlineLoops  = (sndLoopShape == kSongSndLoopInlined);
  const bool groupedLoops = (sndLoopShape == kSongSndLoopGrouped);
  const bool perSample    = (sndLoopShape == kSongSndLoopPerSample);

  // Shared locals live outside the switch, declared only if reachable, so the
  // generated file doesn't warn.
  bool anySounding = false, anySamp = false;
  // `s` only for an unpanned sound on stereo output.
  bool anyMonoOnStereo = false;
  for (const EventInfo& e : events) {
    if (e.audio.synthIdx < 0) continue;
    anySounding = true;
    if (caseUsesSamp(e)) anySamp = true;
    if (stereoOut && !isStereoSound(e.audio.synthIdx)) anyMonoOnStereo = true;
  }

  // Grouped shape: per-instrument tables. Everything but the six scalars below is
  // keyed by synthIdx already, so grouping by it is safe. Columns are emitted only
  // where the body reads them; no columns, no table.
  struct ParamRow { std::string col[6]; };            // hz, xrate, nn, rate, vel, velmul
  static const char* const kParamCol[6] = { "hz", "xrate", "nn", "rate", "vel", "velmul" };
  // Usage slot gating each of the first five columns; velmul exists only if some
  // event of the instrument is below full velocity.
  static const int kParamUsageSlot[5] = { 1, 2, 3, 5, 6 };

  std::vector<int>                     sndOrder;   // dense instrument index -> synthIdx
  std::map<int, int>                   sndDense;   // synthIdx -> dense instrument index
  std::vector<const ResolvedVoice*>    sndVoice;   // dense -> a representative event's voice
  std::vector<bool>                    sndAnyVel;  // dense -> any event below full velocity
  std::vector<std::vector<ParamRow> >  sndRows;    // dense -> deduplicated rows
  std::vector<int> evSnd((size_t)numRows, -1);     // ev slot -> dense instrument (-1 = silent)
  std::vector<int> evRow((size_t)numRows, 0);      // ev slot -> row in that table

  if (groupedLoops) {
    // Pass 1: instrument order, and whether each needs velmul.
    for (const EventInfo& e : events) {
      if (e.audio.synthIdx < 0) continue;
      std::map<int, int>::iterator it = sndDense.find(e.audio.synthIdx);
      if (it == sndDense.end()) {
        sndDense[e.audio.synthIdx] = (int)sndOrder.size();
        sndOrder.push_back(e.audio.synthIdx);
        sndVoice.push_back(&e.audio);
        sndAnyVel.push_back(false);
        sndRows.push_back(std::vector<ParamRow>());
      }
      if (e.hasVel) sndAnyVel[sndDense[e.audio.synthIdx]] = true;
    }
    // Pass 2: deduplicated rows and the ev -> (instrument, row) map.
    for (const EventInfo& e : events) {
      const int slot = e.eventId - kEventIdBase;
      if (e.audio.synthIdx < 0) continue;               // stays -1: no case matches
      const int k = sndDense[e.audio.synthIdx];
      const SoundArgUsage& u = synthUsage[e.audio.synthIdx];
      const int velocity = rows[slot].velocity;
      const std::string vsuf = "_" + std::to_string(e.note) + "_v" + std::to_string(velocity);

      ParamRow r;
      if (u.used[1]) r.col[0] = ConstName(e.audio.ident, e.note, "HZ");
      if (u.used[2]) r.col[1] = ConstName(e.audio.ident, e.note, "XRATE");
      if (u.used[3]) r.col[2] = ConstName(e.audio.ident, e.note, "NN");
      if (u.used[5]) r.col[3] = ConstName(e.audio.ident, e.note, "RATE");
      if (u.used[6]) r.col[4] = e.audio.ident + vsuf + "_VEL";
      if (sndAnyVel[k])
        r.col[5] = e.hasVel ? (e.audio.ident + vsuf + "_VELMUL") : std::string("SONG_VEL_FULL");

      size_t ri = 0;
      for (; ri < sndRows[k].size(); ri++) {
        bool same = true;
        for (int c = 0; c < 6 && same; c++) same = (sndRows[k][ri].col[c] == r.col[c]);
        if (same) break;
      }
      if (ri == sndRows[k].size()) sndRows[k].push_back(r);
      evSnd[slot] = k;
      evRow[slot] = (int)ri;
    }
  }

  // Explicit bool: vector<bool>::operator[] returns a proxy.
  auto groupColUsed = [&](int k, int c) -> bool {
    if (c == 5) return sndAnyVel[k];
    return synthUsage[sndOrder[k]].used[kParamUsageSlot[c]];
  };
  auto groupHasTable = [&](int k) {
    for (int c = 0; c < 6; c++) if (groupColUsed(k, c)) return true;
    return false;
  };
  auto groupUsesSamp = [&](int k) {
    const SoundArgUsage& u = synthUsage[sndOrder[k]];
    return u.used[0] || u.used[2] || hasSample(sndOrder[k]);
  };

  // ev -> instrument/row arrays, replacing the per-event jump table.
  auto emitEvTable = [&](const char* type, const char* name, const char* countMacro,
                         const std::vector<int>& v, int noneAs) {
    linef("static const %s %s[%s] = {", type, name, countMacro);
    std::string line;
    for (size_t s = 0; s < v.size(); s++) {
      char cell[24];
      snprintf(cell, sizeof(cell), "%d,", v[s] < 0 ? noneAs : v[s]);
      if (line.empty()) line = "   ";
      line += " ";
      line += cell;
      if ((s % 16) == 15 || s + 1 == v.size()) { linef("%s", line.c_str()); line.clear(); }
    }
    linef("};");
  };

  if (groupedLoops) {
    const bool anyTable = [&]{ for (size_t k = 0; k < sndOrder.size(); k++) if (groupHasTable((int)k)) return true; return false; }();
    // As narrow as the song needs.
    size_t maxRows = 0;
    for (size_t k = 0; k < sndRows.size(); k++) maxRows = std::max(maxRows, sndRows[k].size());
    const char* rowT = (maxRows <= 256) ? "unsigned char" : "unsigned short";

    linef("// ---- grouped sound loops ------------------------------------------------");
    linef("// One batch loop per instrument (see SongExportInput::sndLoopShape). The");
    linef("// per-(note, velocity) constants each loop needs are in the tables below,");
    linef("// reached through song_ev_snd/song_ev_row; everything else about a sound is");
    linef("// the same for every event that plays it, and so is baked into its loop.");
    linef("#define SONG_VEL_FULL            65536   // mul16(a, SONG_VEL_FULL) == a exactly");
    linef("#define SONG_SND_NONE            %d      // event renders no audio", (int)sndOrder.size());
    linef("#define SONG_SND_EVENT_BASE      %d", kEventIdBase);
    linef("#define SONG_SND_EVENT_COUNT     %d", numRows);
    for (size_t k = 0; k < sndOrder.size(); k++)
      linef("#define SONG_SND_%-15s %d", sndVoice[k]->ident.c_str(), (int)k);
    linef("");

    for (size_t k = 0; k < sndOrder.size(); k++) {
      if (!groupHasTable((int)k)) {
        linef("// %s: every parameter is the same for all %d of its events -- no table.",
              sndVoice[k]->ident.c_str(), (int)sndRows[k].size());
        linef("");
        continue;
      }
      const char* ct = CTypeName(sndVoice[k]->type);
      linef("typedef struct {");
      for (int c = 0; c < 6; c++)
        if (groupColUsed((int)k, c))
          linef("    %s %s;", c == 5 ? "int" : ct, kParamCol[c]);   // velmul is always fx16
      linef("} song_p_%s_t;", sndVoice[k]->ident.c_str());
      linef("static const song_p_%s_t song_p_%s[%d] = {",
            sndVoice[k]->ident.c_str(), sndVoice[k]->ident.c_str(), (int)sndRows[k].size());
      for (size_t ri = 0; ri < sndRows[k].size(); ri++) {
        std::string init;
        for (int c = 0; c < 6; c++) {
          if (!groupColUsed((int)k, c)) continue;
          if (!init.empty()) init += ", ";
          init += sndRows[k][ri].col[c];
        }
        linef("    { %s },", init.c_str());
      }
      linef("};");
      linef("");
    }

    emitEvTable("unsigned char", "song_ev_snd", "SONG_SND_EVENT_COUNT", evSnd, (int)sndOrder.size());
    if (anyTable) emitEvTable(rowT, "song_ev_row", "SONG_SND_EVENT_COUNT", evRow, 0);
    linef("");
  }

  linef("int song_render_audio_batch(int sample_id, song_SongState* state, short int* out_samples)");
  linef("{");
  if (perSample) {
    linef("    song_sequence_tick(sample_id, state);");
    linef("    for (int i = 0; i < BATCHSIZE; i++) {");
    if (stereoOut) linef("        int sampleL = 0, sampleR = 0; // fx16, summed across channels");
    else           linef("        int sample = 0; // fx16, summed across channels");
    linef("        for (int channel_id = 0; channel_id < SONG_CHANNEL_COUNT; channel_id++) {");
    if (anySamp) linef("            int samp = sample_id + i - state->channel_timestamp[channel_id];");
    linef("            switch (state->channel_event[channel_id]) {");
  } else {
    if (stereoOut) {
      linef("    // fx16, summed across channels before the final PCM scale. Two of them:");
      linef("    // a sound whose body reads `pan` is called once per output channel.");
      linef("    int accL[BATCHSIZE], accR[BATCHSIZE];");
    } else {
      linef("    int acc[BATCHSIZE]; // fx16, summed across channels before the final PCM scale");
    }
    linef("    song_sequence_tick(sample_id, state);");
    linef("    for (int i = 0; i < BATCHSIZE; i++)");
    if (stereoOut) linef("        { accL[i] = 0; accR[i] = 0; }");
    else           linef("        acc[i] = 0;");
    linef("    for (int channel_id = 0; channel_id < SONG_CHANNEL_COUNT; channel_id++) {");
    linef("        int ev = state->channel_event[channel_id];");
    linef("        if (ev) {");
  }
  if (groupedLoops) {
    // Bounds check required: an unknown id would index the arrays out of range.
    linef("            int slot = ev - SONG_SND_EVENT_BASE;");
    linef("            if (slot >= 0 && slot < SONG_SND_EVENT_COUNT) {");
    if (anySounding) linef("                int i%s%s;", anySamp ? ", samp" : "",
                            anyMonoOnStereo ? ", s" : "");
    bool anyTableEmitted = false;
    for (size_t k = 0; k < sndOrder.size(); k++) if (groupHasTable((int)k)) anyTableEmitted = true;
    if (anyTableEmitted) linef("                int row = song_ev_row[slot];");
    linef("                switch (song_ev_snd[slot]) { // one batch loop per instrument");
    for (size_t k = 0; k < sndOrder.size(); k++) {
      const ResolvedVoice& v = *sndVoice[k];
      const SoundArgUsage& u = synthUsage[v.synthIdx];
      auto mixFor = [&](double pan) {
        std::string callExpr = v.ident + "("
                             + buildCallArgs(v, u, /*note=*/0, "samp", "(sample_id + i)",
                                             /*velocity=*/0, /*byRef=*/true, pan) + ")";
        std::string mix = BuildFx16CallExpr(callExpr, v.type, synthRetType[v.synthIdx]);
        if (sndAnyVel[k]) mix = "mul16(" + mix + ", p.velmul)";
        return mix;
      };

      std::string body;
      if (groupUsesSamp((int)k)) body += "samp = sample_id + i - state->channel_timestamp[channel_id]; ";
      body += sampleStamp(v);
      body += buildAccum(v.synthIdx, mixFor);

      std::string pre;
      if (groupHasTable((int)k))
        pre = "const song_p_" + v.ident + "_t p = song_p_" + v.ident + "[row]; ";
      pre += sampleBind(v);
      linef("                case SONG_SND_%s: { %sfor (i = 0; i < BATCHSIZE; i++) { %s } } break;",
            v.ident.c_str(), pre.c_str(), body.c_str());
    }
    linef("                }");
    linef("            }");
  } else if (inlineLoops) {
    if (anySounding) linef("            int i%s%s;", anySamp ? ", samp" : "",
                            anyMonoOnStereo ? ", s" : "");
    linef("            switch (ev) { // one specialised batch loop per case");
  } else if (!perSample) {
    linef("            for (int i = 0; i < BATCHSIZE; i++) {");
    if (anySamp) linef("                int samp = sample_id + i - state->channel_timestamp[channel_id];");
    if (stereoOut) linef("                int sampleL = 0, sampleR = 0; // fx16, one per output channel");
    else           linef("                int sample = 0; // fx16");
    linef("                switch (ev) {");
  }
  // The inlined shape has no enclosing batch loop, so labels sit shallower.
  const char* ci = (inlineLoops || perSample) ? "                " : "                    ";
  for (size_t ei = 0; !groupedLoops && ei < events.size(); ) {
    size_t ej = ei + 1;
    while (ej < events.size() && sameIdentity(events[ei], events[ej])) ej++;
    const EventInfo& e = events[ej - 1];
    size_t first = ei;
    ei = ej;
    if (e.audio.synthIdx < 0) {
      // Drop the whole fall-through group, or its labels would run the next case.
      if (!in.addEmptyCases) continue;
      emitFallThroughLabels(first, ej, ci);
      // Channel printed 1-based.
      linef("%scase %d: break; // (channel %d note %d has no sound)",
            ci, e.eventId, rows[e.eventId - kEventIdBase].channel + 1, e.note);
      continue;
    }
    emitFallThroughLabels(first, ej, ci);
    auto mixFor = [&](double pan) { return buildMixExpr(e, pan); };

    if (inlineLoops) {
      // case N: <bind> for (i = 0; i < BATCHSIZE; i++) { <samp> <stamp> acc[i] += <mix>; } break;
      std::string body;
      if (caseUsesSamp(e)) body += "samp = sample_id + i - state->channel_timestamp[channel_id]; ";
      body += sampleStamp(e.audio);
      body += buildAccum(e.audio.synthIdx, mixFor);
      linef("%scase %d: %sfor (i = 0; i < BATCHSIZE; i++) { %s } break;",
            ci, e.eventId, sampleBind(e.audio).c_str(), body.c_str());
    } else if (perSample) {
      std::string pre = samplePreamble(e.audio);
      if (!stereoOut)
        linef("%scase %d: %ssample += %s; break;", ci, e.eventId, pre.c_str(), mixFor(0.0).c_str());
      else if (isStereoSound(e.audio.synthIdx))
        linef("%scase %d: %ssampleL += %s; sampleR += %s; break;",
              ci, e.eventId, pre.c_str(), mixFor(-1.0).c_str(), mixFor(1.0).c_str());
      else
        linef("%scase %d: { %sint s = %s; sampleL += s; sampleR += s; } break;",
              ci, e.eventId, pre.c_str(), mixFor(0.0).c_str());
    } else if (!stereoOut) {
      linef("%scase %d: %ssample = %s; break;",
            ci, e.eventId, samplePreamble(e.audio).c_str(), mixFor(0.0).c_str());
    } else if (isStereoSound(e.audio.synthIdx)) {
      linef("%scase %d: %ssampleL = %s; sampleR = %s; break;",
            ci, e.eventId, samplePreamble(e.audio).c_str(),
            mixFor(-1.0).c_str(), mixFor(1.0).c_str());
    } else {
      // Unpanned: one call for both channels.
      linef("%scase %d: %ssampleR = sampleL = %s; break;",
            ci, e.eventId, samplePreamble(e.audio).c_str(), mixFor(0.0).c_str());
    }
  }
  if (perSample) {
    linef("            }");
    linef("        }");
    if (stereoOut) {
      linef("        out_samples[2*i] = song_fx16_to_pcm16(sampleL);");
      linef("        out_samples[2*i + 1] = song_fx16_to_pcm16(sampleR);");
    } else {
      linef("        out_samples[i] = song_fx16_to_pcm16(sample);");
    }
    linef("    }");
  } else {
    if (groupedLoops) {
    } else if (inlineLoops) {
      linef("            }");
    } else {
      linef("                }");
      if (stereoOut) linef("                accL[i] += sampleL; accR[i] += sampleR;");
      else           linef("                acc[i] += sample;");
      linef("            }");
    }
    linef("        }");
    linef("    }");
    linef("    for (int i = 0; i < BATCHSIZE; i++)");
    if (stereoOut) {
      // Interleaved L,R.
      linef("        { out_samples[2*i] = song_fx16_to_pcm16(accL[i]);");
      linef("          out_samples[2*i + 1] = song_fx16_to_pcm16(accR[i]); }");
    } else {
      linef("        out_samples[i] = song_fx16_to_pcm16(acc[i]);");
    }
  }
  linef("    return sample_id + BATCHSIZE;");
  linef("}");
  linef("");

  // (4) song_visual_render(): once per call, not per sample; no mixing.
  auto visualIdentFor = [&](const EventInfo& e) -> const std::string* {
    if (e.visual.synthIdx < 0) return nullptr;
    auto it = visualIdent.find(e.visual.synthIdx);
    return it == visualIdent.end() ? nullptr : &it->second;
  };
  // Keyed on the visual body, while the bound sample comes from the audio voice.
  auto visualNeedsSmp = [&](const EventInfo& e) {
    if (e.visual.synthIdx < 0) return false;
    std::map<int, bool>::const_iterator it = visualSmp.find(e.visual.synthIdx);
    return it != visualSmp.end() && it->second;
  };
  bool anyVisualSamp = false;
  bool anyVisual = false;
  for (const EventInfo& e : events) {
    if (!visualIdentFor(e)) continue;
    anyVisual = true;
    const SoundArgUsage& vu = visualUsage[e.visual.synthIdx];
    if (vu.used[0] || vu.used[2] || visualNeedsSmp(e)) anyVisualSamp = true;
  }

  // Grouped visual switch: the per-(note, velocity) scalars, plus the sample
  // pointer for bodies calling smp().
  const bool groupedVis = (in.visSwitchShape == kSongVisSwitchGrouped);

  struct VisRow { std::string col[6]; };            // hz, xrate, nn, rate, vel, smp
  static const char* const kVisCol[6] = { "hz", "xrate", "nn", "rate", "vel", "smp" };
  static const int kVisUsageSlot[5] = { 1, 2, 3, 5, 6 };

  std::vector<int>                    visOrder;   // dense visual index -> visual synthIdx
  std::map<int, int>                  visDense;
  std::vector<const ResolvedVoice*>   visVoice;   // dense -> a representative event's visual voice
  std::vector<std::vector<VisRow> >   visRows;
  std::vector<int> evVis((size_t)numRows, -1);    // ev slot -> dense visual (-1 = draws nothing)
  std::vector<int> evVRow((size_t)numRows, 0);

  auto visColUsed = [&](int k, int c) -> bool {
    const int si = visOrder[k];
    if (c == 5) return visualSmp[si];
    return visualUsage[si].used[kVisUsageSlot[c]];
  };
  auto visHasTable = [&](int k) {
    for (int c = 0; c < 6; c++) if (visColUsed(k, c)) return true;
    return false;
  };

  if (groupedVis) {
    for (const EventInfo& e : events) {
      if (!visualIdentFor(e)) continue;
      const int slot = e.eventId - kEventIdBase;
      const int si   = e.visual.synthIdx;
      if (visDense.find(si) == visDense.end()) {
        visDense[si] = (int)visOrder.size();
        visOrder.push_back(si);
        visVoice.push_back(&e.visual);
        visRows.push_back(std::vector<VisRow>());
      }
      const int k = visDense[si];
      const SoundArgUsage& vu = visualUsage[si];
      const int velocity = rows[slot].velocity;

      VisRow r;
      if (vu.used[1]) r.col[0] = ConstName(e.visual.ident, e.note, "HZ");
      if (vu.used[2]) r.col[1] = ConstName(e.visual.ident, e.note, "XRATE");
      if (vu.used[3]) r.col[2] = ConstName(e.visual.ident, e.note, "NN");
      if (vu.used[5]) r.col[3] = ConstName(e.visual.ident, e.note, "RATE");
      if (vu.used[6]) r.col[4] = e.visual.ident + "_" + std::to_string(e.note) + "_v"
                               + std::to_string(velocity) + "_VEL";
      // No sample: a null row, and the bind is skipped.
      if (visualSmp[si])
        r.col[5] = hasSample(e.audio.synthIdx) ? ("&smp_" + synthIdent[e.audio.synthIdx])
                                               : std::string("0");

      size_t ri = 0;
      for (; ri < visRows[k].size(); ri++) {
        bool same = true;
        for (int c = 0; c < 6 && same; c++) same = (visRows[k][ri].col[c] == r.col[c]);
        if (same) break;
      }
      if (ri == visRows[k].size()) visRows[k].push_back(r);
      evVis[slot]  = k;
      evVRow[slot] = (int)ri;
    }

    bool anyVisTable = false;
    for (size_t k = 0; k < visOrder.size(); k++) if (visHasTable((int)k)) anyVisTable = true;
    size_t maxVisRows = 0;
    for (size_t k = 0; k < visRows.size(); k++) maxVisRows = std::max(maxVisRows, visRows[k].size());
    const char* vrowT = (maxVisRows <= 256) ? "unsigned char" : "unsigned short";

    if (!visOrder.empty()) {
      linef("// ---- grouped visual cases -----------------------------------------------");
      linef("// One switch case per visual instrument (see SongExportInput::visSwitchShape).");
      linef("// The per-(note, velocity) constants each body needs are in the tables below,");
      linef("// reached through song_ev_vis/song_ev_vrow; everything else about a visual is");
      linef("// the same for every event that draws it, and so is baked into its case.");
      linef("#define SONG_VIS_NONE            %d      // event draws nothing", (int)visOrder.size());
      linef("#define SONG_VIS_EVENT_BASE      %d", kEventIdBase);
      linef("#define SONG_VIS_EVENT_COUNT     %d", numRows);
      for (size_t k = 0; k < visOrder.size(); k++)
        linef("#define SONG_VIS_%-15s %d", visualBase[visOrder[k]].c_str(), (int)k);
      linef("");

      for (size_t k = 0; k < visOrder.size(); k++) {
        const std::string& base = visualBase[visOrder[k]];
        if (!visHasTable((int)k)) {
          linef("// %s: every parameter is the same for all %d of its events -- no table.",
                visualIdent[visOrder[k]].c_str(), (int)visRows[k].size());
          linef("");
          continue;
        }
        const char* ct = CTypeName(visVoice[k]->type);
        linef("typedef struct {");
        for (int c = 0; c < 6; c++)
          if (visColUsed((int)k, c))
            linef("    %s %s;", c == 5 ? "const song_sample_t *" : ct, kVisCol[c]);
        linef("} song_pv_%s_t;", base.c_str());
        linef("static const song_pv_%s_t song_pv_%s[%d] = {",
              base.c_str(), base.c_str(), (int)visRows[k].size());
        for (size_t ri = 0; ri < visRows[k].size(); ri++) {
          std::string init;
          for (int c = 0; c < 6; c++) {
            if (!visColUsed((int)k, c)) continue;
            if (!init.empty()) init += ", ";
            init += visRows[k][ri].col[c];
          }
          linef("    { %s },", init.c_str());
        }
        linef("};");
        linef("");
      }

      emitEvTable("unsigned char", "song_ev_vis", "SONG_VIS_EVENT_COUNT", evVis, (int)visOrder.size());
      if (anyVisTable) emitEvTable(vrowT, "song_ev_vrow", "SONG_VIS_EVENT_COUNT", evVRow, 0);
      linef("");
    }
  }

  linef("int song_visual_render(int sample_id, song_SongState* state)");
  linef("{");
  linef("    song_sequence_tick(sample_id, state);");
  linef("    for (int channel_id = 0; channel_id < SONG_CHANNEL_COUNT; channel_id++) {");
  linef("        int ev = state->channel_event[channel_id];");
  linef("        if (ev) {");
  // Grouped: range-check before indexing.
  const char* vi = "                ";     // case indent
  const char* vb = "            ";         // body indent inside `if (ev)`
  if (groupedVis && !visOrder.empty()) {
    linef("            int slot = ev - SONG_VIS_EVENT_BASE;");
    linef("            if (slot >= 0 && slot < SONG_VIS_EVENT_COUNT) {");
    vb = "                ";
    vi = "                ";
  }
  if (anyVisualSamp) linef("%sint samp = sample_id - state->channel_timestamp[channel_id];", vb);
  // Per-body reset of images and targets; only emitted with visual bodies.
  if (anyVisual) linef("%svscreen_images_reset();", vb);

  if (groupedVis && !visOrder.empty()) {
    bool anyVisTable = false;
    for (size_t k = 0; k < visOrder.size(); k++) if (visHasTable((int)k)) anyVisTable = true;
    if (anyVisTable) linef("%sint vrow = song_ev_vrow[slot];", vb);
    linef("%sswitch (song_ev_vis[slot]) { // one case per visual instrument", vb);
    for (size_t k = 0; k < visOrder.size(); k++) {
      const int si = visOrder[k];
      const ResolvedVoice& v = *visVoice[k];
      const SoundArgUsage& vu = visualUsage[si];
      // `pan` is folded to 0 for visuals.
      std::string args = buildCallArgs(v, vu, /*note=*/0, "samp", "sample_id",
                                       /*velocity=*/0, /*byRef=*/true, /*pan=*/0.0);
      std::string body;
      if (visHasTable((int)k))
        body += "const song_pv_" + visualBase[si] + "_t p = song_pv_" + visualBase[si] + "[vrow]; ";
      // The sample comes from the table, null when none.
      if (visualSmp[si])
        body += "if (p.smp) { song_smp_bind(&song_voices[channel_id], p.smp, SONG_SAMPLE_RATE);"
                " song_current_voice = &song_voices[channel_id];"
                " song_voices[channel_id].note_sample = samp; } ";
      body += visualIdent[si] + "(" + args + ");";
      linef("%scase SONG_VIS_%s: { %s } break;", vi, visualBase[si].c_str(), body.c_str());
    }
    linef("%s}", vb);
    linef("            }");     // closes the bounds check
  } else {
    linef("            switch (ev) {");
    for (size_t ei = 0; ei < events.size(); ) {
      size_t ej = ei + 1;
      while (ej < events.size() && sameIdentity(events[ei], events[ej])) ej++;
      const EventInfo& e = events[ej - 1];
      size_t first = ei;
      ei = ej;
      const std::string* vIdent = visualIdentFor(e);
      if (!vIdent) {
        // Drop labels with the body, as in the audio switch.
        if (!in.addEmptyCases) continue;
        emitFallThroughLabels(first, ej, vi);
        linef("%scase %d: break; // no visual", vi, e.eventId);
        continue;
      }
      emitFallThroughLabels(first, ej, vi);
      const SoundArgUsage& vu = visualUsage[e.visual.synthIdx];
      int velocity = rows[e.eventId - kEventIdBase].velocity;
      std::string args = buildCallArgs(e.visual, vu, e.note, "samp", "sample_id", velocity,
                                       /*byRef=*/false, /*pan=*/0.0);
      const std::string pre = visualNeedsSmp(e) ? samplePreamble(e.audio) : std::string();
      linef("%scase %d: %s%s(%s); break;",
            vi, e.eventId, pre.c_str(), vIdent->c_str(), args.c_str());
    }
    linef("            }");
  }
  linef("        }");
  linef("    }");
  linef("    return sample_id;");
  linef("}");

  // (5) song_total_samples(): past the last pattern song_sequence_tick keeps
  // channels latched, so players need the end. Over SONG_SAMPLES_PER_SONGTICK so
  // it retimes.
  linef("");
  linef("// ===== song length =====");
  linef("// Total playable length in samples: every pattern, at this build's tick.");
  linef("// Playback should stop once sample_id reaches it -- past the last pattern");
  linef("// song_sequence_tick returns without clearing the channels, so the final");
  linef("// events would sustain forever.");
  linef("int song_total_samples(void)");
  linef("{");
  linef("    return SONG_PATTERN_COUNT * (1 << SONG_PATTERN_LEN_SHIFT) * SONG_SAMPLES_PER_SONGTICK;");
  linef("}");

  return true;
}

bool SongExportGenerateH(const SongExportInput& in, std::string& out, std::string& err,
                         int outputChannels)
{
  out.clear();
  err.clear();

  if (in.seq.empty()) { err = "no recorded sequence"; return false; }

  // Must match SongExportGenerateC's call.
  CompressedSequence cs = CompressEventMatrix(in.seq.matrix, (int)in.seq.rows.size(), in.seq.cols, BuildRowOrders(in));
  if (cs.numRows == 0) { err = "event matrix failed to compress"; return false; }

  const int batchSize = in.batchSize > 0 ? in.batchSize : 32;

  out += "// Auto-generated by \"Save C Song\" -- public interface of song.c.\n";
  out += "// Do not edit, and do not copy anything out of this file into another\n";
  out += "// header: SONG_CHANNEL_COUNT (and so song_SongState's layout) is\n";
  out += "// re-derived from the recorded sequence on every export.\n";
  out += "#ifndef SONG_H\n";
  out += "#define SONG_H\n";
  out += "\n";
  out += ExportToCHeader(cs, "song");
  out += "\n";
  out += "// Samples produced per song_render_audio_batch() call (song.c's BATCHSIZE).\n";
  out += "// An audio glue layer's chunk size must match this.\n";
  out += "#define SONG_BATCH_SAMPLES " + std::to_string(batchSize) + "\n";
  out += "\n";
  out += "// Output channels: 1 (mono) or 2 (stereo, INTERLEAVED L,R,L,R...).\n";
  out += "//\n";
  out += "// Like SONG_CHANNEL_COUNT above, this is re-derived on every export -- under\n";
  out += "// the exporter's Auto mode it is 2 only if some sound's body reads the `pan`\n";
  out += "// argument, so it changes when the SOUNDS do. Never hard-code it and never\n";
  out += "// copy it into another header: it sizes out_samples, and a consumer that\n";
  out += "// disagrees either drops half the audio or writes past the end of its buffer.\n";
  out += "#define SONG_OUTPUT_CHANNELS " + std::to_string(outputChannels == 2 ? 2 : 1) + "\n";
  out += "\n";
  out += "// Renders SONG_BATCH_SAMPLES samples starting at sample_id into out_samples,\n";
  out += "// advancing the sequencer via *state, and returns the next sample_id. Zero\n";
  out += "// *state before the first call.\n";
  out += "// out_samples holds SONG_BATCH_SAMPLES * SONG_OUTPUT_CHANNELS shorts.\n";
  out += "int song_render_audio_batch(int sample_id, song_SongState* state, short int* out_samples);\n";
  out += "\n";
  out += "// Draws the song's visuals for playback position sample_id, through the same\n";
  out += "// sequencer but with its own caller-owned *state, so it does\n";
  out += "// not advance the audio path's note phases. Visual bodies draw via vscreen_*.\n";
  out += "int song_visual_render(int sample_id, song_SongState* state);\n";
  out += "\n";
  out += "// Total playable length of the song in samples; playback should stop once\n";
  out += "// sample_id reaches it. Past the last pattern the sequencer returns without\n";
  out += "// clearing the channels, so the final events would otherwise sustain forever.\n";
  out += "int song_total_samples(void);\n";
  out += "\n";
  out += "#endif // SONG_H\n";
  return true;
}

namespace {
bool WriteOrReport(const std::string& path, const std::string& text, std::string& err)
{
  if (WriteWholeFile(path, text)) return true;
  err = "cannot write '" + path + "'";
  return false;
}

// "dir/song.c" -> "dir/song.h" (appends .h if there's no extension to replace).
std::string HeaderPathFor(const std::string& cPath)
{
  size_t dot = cPath.find_last_of('.');
  size_t sep = cPath.find_last_of("/\\");
  if (dot == std::string::npos || (sep != std::string::npos && dot < sep))
    return cPath + ".h";
  return cPath.substr(0, dot) + ".h";
}
} // namespace

bool SongExportWriteFile(const SongExportInput& in, const std::string& path, std::string& err)
{
  // Generate both before writing either.
  std::string cText, hText;
  int channels = 1;
  if (!SongExportGenerateC(in, cText, err, &channels)) return false;
  // `channels` comes from the C pass, never re-derived.
  if (!SongExportGenerateH(in, hText, err, channels)) return false;

  if (!WriteOrReport(HeaderPathFor(path), hText, err)) return false;
  return WriteOrReport(path, cText, err);
}
